---
title: "Data 605 Assignment-13"
author: "Deepak Mongia"
date: "May 5, 2019"
output: html_document
---

##1. Use integration by substitution to solve the integral below.

### $\int 4 e^{-7x} dx$

### Using substitution
### $u = -7x$
### $du/dx = d/dx (-7x) = -7$
### $du = -7 dx$

### Hence
### $\int 4 e^{-7x} dx = \int -1/7 (-7) 4 e^{-7x} dx$
### $= -1/7 \int 4 e^{-7x} (-7dx) = -1/7 \int 4 e^u du$
### $= -1/7 \int 4 e^{-7x} (-7dx) = -1/7 \int 4 e^u du$
### $= -4/7 \int e^u du = -(4/7) e^u + C$

### Replacing u with the value -7x
### $= -(4/7) e^{-7x} + C$


##2. Biologists are treating a pond contaminated with bacteria. The level of contamination is changing at a rate of $dN/dt = -(3150/t^4) - 220$ bacteria per cubic centimeter per day, where t is the number of days since treatment began. Find a function N( t ) to estimate the level of contamination if the level after 1 day was 6530 bacteria per cubic centimeter.

### Contamination N of the pond will be derived by taking the integral of the change rate: dN/dt.
### $N = \int dN/dt = \int (-(3150/t^4) - 220)$ dt
### $N = -3150 t^{-3}/(-3) - 220t + C = 1050 t^{-3} - 220t + C$ 

### At t = 1 day, N = 6530
### Hence substituting t = 1,
### $6530 = 1050 (1)^{-3} - 220(1) + C$
### $C = 5700$

### Hence the function to describe the level of contamination, N at a given time t is:
### $N(t) = 1050 t^{-3} - 220t + 5700$


##3. Find the total area of the red rectangles in the figure below, where the 3. equation of the line is f ( x ) = 2x - 9.

###$Area = \int_{4.5}^{8.5} (2x - 9)$ dx
###$Area = ({8.5}^2 - 9(8.5) + C) - ({4.5}^2 - 9(4.5) + C) = 16$ 


##4. Find the area of the region bounded by the graphs of the given equations.
###$y = x^2 - 2x - 2, y = x + 2$ 

### Plotting the 2 functions first
```{r}
fun1 <- function(x)
{
  x^2 - 2*x - 2
}

fun2 <- function(x)
{
  x + 2
}

curve(fun1, -6, 6)
plot(fun2, -6, 6, add=TRUE)
```

Calculating the solutions, where the 2 graphs meet.

$x^2 - 2x - 2 = x + 2$

$x^2 - 3x - 4 = 0$

$(x-4)(x+1) = 0$

Hence, the solutions are present at the x-values x = 4, and x = -1

Getting y for these values, the 2 points are (4,6) and (-1,1)

Now to get the area between the 2 curves, area will be the difference between the areas of the 2 curves, which means the difference in the integrals between x=-1 and x=4

$Area = \int_{-1}^4 (x+2) - (x^2 - 2x - 2) $
= 20.83


##5. A beauty supply store expects to sell 110 flat irons during the next year. It costs $3.75 to store one flat iron for one year. There is a fixed cost of $8.25 for each order. Find the lot size and the number of orders per year that will minimize inventory costs.

## Let  x = no. of orders per year
##      y = lot size

No. of irons produced per year = x * y, which should be greater than or equal to 110
x*y >= 110

No. of extra irons, not sold, which will be added to the cost of storage, which is $3.75 per iron.

Inventory cost = 3.75 (x*y - 110) + 8.75 * x

For minimum inventory cost, we will minimize x, that means x = 1. Hence y = 110

Hence, for minimum inventory costs, 1 order of size 110 will be optimum.


##6. Use integration by parts to solve the integral below.
## $\int (x^6)ln(9x)$ dx

### As per the integration by parts formula:
### $\int f(x)\overline{g}(x) $  dx