---
title: "DMongia_Assignment4 Data 605.Rmd"
author: "Deepak Mongia"
date: "February 24, 2019"
output: html_document
---


1. Problem Set 1

```{r}
A <- matrix(c(1, 2, 3, -1, 0, 4), nrow = 2, byrow = TRUE)
print(A)

X <- A %*% t(A)
print(X)

Y <- t(A) %*% A
print(Y)
```

Computing the Eigen values and Eigen vectors of X and Y
```{r}
lambda_x <- eigen(X)$values
print(lambda_x)

lambda_y <- eigen(Y)$values
print(lambda_y)


s_x <- eigen(X)$vectors
print(s_x)

s_y <- eigen(Y)$vectors
print(s_y)

```

Generating SVD:
```{r}
svd_a <- svd(A)
print(svd_a)
```

As we see above, $u and $v are same as the Eigenvectors given above as these can be easily generated by a scalar multiplication of the Eigenvectors.




2. Problem Set 2

```{r}
library(Matrix)

myinverse = function(A)
{
### First check - is the input matrix a full-rank square matrix
  if (!(nrow(A) == ncol(A) & rankMatrix(A) == nrow(A)))
  {
    return("Not a full-rank square matrix")
  }
  else
  {
    Asize = nrow(A)
    ## Create a dummy matrix to create the matrix of the co-factors
    Cofactor_matrix <- matrix(nrow = Asize, ncol = Asize)
    for (i in 1:Asize) {
      for (j in 1:Asize) {
        Cofactor_matrix[i,j] <- (-1)^(i+j) * det(A[-i,-j])
      }
    }
    ## Now we have the cofactor matrix ready, we will use the fornula to get inverse of A:
    ## A inverse = (Transpose of Cofactor matrix of A) / det(A)
    inverse_matrix <- t(Cofactor_matrix) / det(A)
    return(inverse_matrix)
  }
    
}

```


Testing:
```{r}
library(dplyr)
test_matrix <- matrix(c(2,3,2,1,2,1,1,1,2),nrow = 3)

test_matrix

solve(test_matrix)

myinverse(test_matrix)

identical(solve(test_matrix) %>% round(6), myinverse(test_matrix) %>% round(6))
```

